name: fin_control
description: "Personal expense manager"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI/intl/http
  cupertino_icons: ^1.0.8
  intl: ^0.19.0
  http: ^1.2.2

  # Хранилище
  sqflite: ^2.3.3
  path: ^1.9.0

  # Камера/медиа
  image_picker: ^1.1.2

  # Персист пользовательских категорий
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  # Для тестов на десктопе/CI (инициализируем в test/flutter_test_config.dart)
  sqflite_common_ffi: ^2.3.0

flutter:
  uses-material-design: true
